title: Vinu Sankar Sadasivan
position: Junior Research Fellow
affiliation: IIT Gandhinagar, India
email: vinu [dot] sankar [at] iitgn.ac.in
random: sankar
keywords: vinu sankar sadasivan, machine learning, research, vinu, sankar, shankar, sadasivan, artificial intelligence
google_scholar: https://scholar.google.com/citations?user=y1IKIw0AAAAJ&hl=en&oi=ao
github_link: #https://github.com/yaoyao-liu/minimal-light
twitter: https://twitter.com/imVinusankars
linkedin: https://www.linkedin.com/in/vinusankars
cv: ./assets/docs/Curriculum_Vitae_public.pdf
avatar: ./assets/img/avatar1.png
google_analytics: UA-179771578-1
favicon: ./assets/img/favicon1.png
favicon_dark: ./assets/img/favicon-dark1.png
description: Vinu Sankar Sadasivan is a JRF at IIT Gandhinagar interested in machine learning research.
canonical: https://vinusankars.github.io/
remote_theme: #yaoyao-liu/minimal-light
